config/routes.rb
CellularAutomaton::Application.routes.draw do
  resources :automatons

  root to: 'automatons#index'

end

app/models/automaton.rb
class Automaton < ActiveRecord::Base
  attr_accessible :rule, :input_state

  def display
    state = init_state 
    max = 64
    str = ''

    max.times do |gen|
      (max - gen).times { str << ' ' }
      state.each { |x| x == 1 ? str << '*' : str << ' ' }
      str << "\n"
      state = evolve(rule, state)
      str
    end

    str
  end

  private

  def init_state
    result = []
    s_arr = input_state.to_s.split('')
    s_arr.each do |s|
      result << s.to_i
    end

    result
  end

  def evolve(rule, state)
    def state.[](x)
      (x < 0 or x >= length) ? 0 : fetch(x)
    end
    next_state = []
    for i in (-1..state.length+1)
      bit = state[i + 1] | (state[i] << 1) | (state[i - 1] << 2)
      mask = 1 << bit
      next_state[i + 1] = ((mask & rule) != 0) ? 1 : 0
    end
    return next_state
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/automatons_controller.rb
class AutomatonsController < ApplicationController
  inherit_resources
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/automatons_helper.rb
module AutomatonsHelper
end

app/views/automatons/_automaton.html.erb
<li><%= link_to("Automaton: rule \##{automaton.rule}", automaton_path(automaton)) %></li>

app/views/automatons/index.html.erb
<%= link_to("New Automaton", new_automaton_path) %>
<ul>
  <%= render @automatons %>
</ul>

app/views/automatons/new.html.erb
<%= simple_form_for @automaton do |f| %>
  <%= f.input :rule %>
  <%= f.input :input_state %>
  <%= f.button :submit %>
<% end %>

app/views/automatons/show.html.erb
<pre><%= @automaton.display %></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CellularAutomaton</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>